language: cpp
os:
    - osx
    - linux
compiler:
    - clang
notifications:
    email: false
env:
    matrix:
        - JULIAVERSION="releases"
        - JULIAVERSION="nightlies"
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./CI/install_julia_osx.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./CI/install_julia_linux.sh; fi
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
    - julia -e 'versioninfo(); Pkg.init(); Pkg.clone(pwd())'
    - julia ./test/test.jl
