language: julia
os:
    - osx
    - linux

julia:
    - 0.7
    - 1.0
    - nightly

# # uncomment the following lines to allow failures on nightly julia
# # (tests will run but not make your overall status red)
# matrix:
#   allow_failures:
#   - julia: 0.7
#   - julia: 1.0
#   - julia: nightly

notifications:
    email: false

after_success:
    - julia -e 'cd(Pkg.dir("Nettle")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
