language: julia
os:
  - osx
  - linux
  - windows

julia:
  - 1.3
  - 1.4
  - nightly

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';
